import express from "express";
import { createServer } from "http";
import { describe, expect, it, vi } from "vitest";

const host = { id: 7, userId: 3, managementId: "u-demo", hostname: "ip-ab12cd34.co08.art", ip: "208.72.218.153", status: "active", expiresAt: null, createdAt: new Date(), ttl: 300 };
vi.mock("./hostService", () => ({ verifyManagementProof: (_id: string, proof?: string) => proof === "valid-proof", createManagedHost: async () => ({ ...host, managementId: "u-new", managementProof: "proof-new", hostname: "ip-new12345.co08.art", sshCommand: "ssh root@ip-new12345.co08.art" }) }));
vi.mock("./db", () => ({ getHostByManagementId: async (id: string) => id === "u-demo" ? host : undefined, getDnsRecord: async () => ({ hostId: 7, cloudflareRecordId: "dns-7", deletedAt: null }), markDnsDeleted: async () => undefined, markHost: async () => undefined, addAuditLog: async () => undefined }));
vi.mock("./cloudflare", () => ({ deleteDnsRecord: async () => undefined }));
import { createManagementRouter } from "./managementRoutes";

async function request(path: string, method = "GET") { const app = express(); app.use(express.json()); app.use("/api/manage", createManagementRouter()); const server = createServer(app); await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); const response = await fetch(`http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}${path}`, { method, headers: { "content-type": "application/json", "x-co08-proof": "valid-proof" }, body: method === "POST" ? JSON.stringify({ proof: "valid-proof" }) : undefined }); server.close(); return response; }

describe("management routes", () => { it("requires proof when absent", async () => { const app = express(); app.use(express.json()); vi.resetModules(); expect(true).toBe(true); app.use("/api/manage", createManagementRouter()); const server = createServer(app); await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); const response = await fetch(`http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}/api/manage/u-demo`); server.close(); expect(response.status).toBe(401); }); it("looks up sanitized host data", async () => { const response = await request("/api/manage/u-demo"); expect(response.status).toBe(200); expect((await response.json()).hostname).toBe("ip-ab12cd34.co08.art"); }); it("stops a host with proof", async () => { const response = await request("/api/manage/u-demo/stop", "POST"); expect(response.status).toBe(200); expect((await response.json()).status).toBe("deleted"); }); it("regenerates a host and returns a new proof", async () => { const response = await request("/api/manage/u-demo/regenerate", "POST"); const body = await response.json(); expect(response.status).toBe(201); expect(body.management_id).toBe("u-new"); expect(body.management_proof).toBe("proof-new"); }); });
